development:
  adapter: mysql2
  encoding: utf8
  database: vyapari_development
  username: root
  password: 
  port: 3306
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: vyapari_test
  username: root
  password: 
  port: 3306
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: vyapari_production
  username: root
  password: 
  port: 3306
  host: localhost
